#!/bin/sh
mkdir -p /var/lib/nginx/tmp /run/nginx
chown -R nginx:nginx /var/lib/nginx /run/nginx
WEB_PORT="${WEB_PORT:-25500}"
SUBCONVERTER_BACKEND_PORT="${SUBCONVERTER_BACKEND_PORT:-${SUBCONVERTER_LISTEN_PORT:-25501}}"
export WEB_PORT
export SUBCONVERTER_BACKEND_PORT
envsubst '${WEB_PORT} ${SUBCONVERTER_BACKEND_PORT}' < /etc/nginx/nginx.conf.tmpl > /etc/nginx/http.d/subconverter.conf
