#!/bin/sh
mkdir -p /var/lib/nginx/tmp /run/nginx
chown -R nginx:nginx /var/lib/nginx /run/nginx
WEB_PORT="${WEB_PORT:-8080}"
export WEB_PORT
envsubst '${WEB_PORT}' < /etc/nginx/nginx.conf.tmpl > /etc/nginx/http.d/subconverter.conf
